-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.distress_limits
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    project_id character varying COLLATE pg_catalog."default",
    roughness_limit numeric,
    rutting_limit numeric,
    cracking_limit numeric,
    ravelling_limit numeric,
    CONSTRAINT distress_limits_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.distress_segments
(
    start_chainage_m integer NOT NULL,
    end_chainage_m integer NOT NULL,
    length_m integer NOT NULL,
    geom_start geography,
    geom_end geography,
    roughness_bi numeric,
    rut_depth_mm numeric,
    crack_area_pct numeric,
    ravelling_area_pct numeric,
    lane_id character varying COLLATE pg_catalog."default" NOT NULL,
    id character varying COLLATE pg_catalog."default" NOT NULL,
    created_at bigint,
    updarted_at bigint,
    CONSTRAINT distress_segments_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.inspection
(
    project_id character varying COLLATE pg_catalog."default",
    inspection_date bigint,
    remarks character varying COLLATE pg_catalog."default",
    inspection_by character varying COLLATE pg_catalog."default",
    inspection_duration character varying COLLATE pg_catalog."default",
    video_link character varying COLLATE pg_catalog."default",
    created_at bigint,
    id character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT inspection_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.lanes
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    project_id character varying COLLATE pg_catalog."default",
    lane_code character varying COLLATE pg_catalog."default",
    lane_number integer,
    side character varying COLLATE pg_catalog."default",
    CONSTRAINT lanes_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.piu_master
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    piu_name character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    pd_name character varying COLLATE pg_catalog."default",
    pincode character varying COLLATE pg_catalog."default",
    created_at bigint,
    updated_at bigint,
    ro_id_fk character varying COLLATE pg_catalog."default",
    CONSTRAINT piu_master_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.projects
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    project_name character varying COLLATE pg_catalog."default",
    upc character varying COLLATE pg_catalog."default",
    piu_id_fk character varying COLLATE pg_catalog."default",
    survey_date bigint,
    year integer,
    cycle integer,
    concessionaire character varying COLLATE pg_catalog."default",
    completion_year bigint,
    mode character varying COLLATE pg_catalog."default",
    length numeric,
    "ae/ie" character varying COLLATE pg_catalog."default",
    CONSTRAINT projects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ro_master
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    ro_name character varying COLLATE pg_catalog."default" NOT NULL,
    ro_resp character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default",
    address character varying COLLATE pg_catalog."default",
    pincode character varying COLLATE pg_catalog."default",
    created_at bigint,
    updated_at bigint,
    CONSTRAINT ro_master_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id character varying COLLATE pg_catalog."default" NOT NULL,
    username character varying COLLATE pg_catalog."default",
    hashpass character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    email character varying COLLATE pg_catalog."default",
    phone character varying COLLATE pg_catalog."default",
    role character varying COLLATE pg_catalog."default",
    status boolean,
    created_at bigint,
    updated_at bigint,
    CONSTRAINT user_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.distress_limits
    ADD CONSTRAINT distress_limits_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.distress_segments
    ADD CONSTRAINT distress_segments_lane_id_fkey FOREIGN KEY (lane_id)
    REFERENCES public.lanes (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.inspection
    ADD CONSTRAINT inspection_inspection_by_fkey FOREIGN KEY (inspection_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.inspection
    ADD CONSTRAINT inspection_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.lanes
    ADD CONSTRAINT lanes_project_id_fkey FOREIGN KEY (project_id)
    REFERENCES public.projects (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.piu_master
    ADD CONSTRAINT piu_master_ro_id_fk_fkey FOREIGN KEY (ro_id_fk)
    REFERENCES public.ro_master (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.projects
    ADD CONSTRAINT projects_piu_id_fk_fkey FOREIGN KEY (piu_id_fk)
    REFERENCES public.piu_master (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;